name: Deploy to Production

on:
  push:
    branches:
      - frontend
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 206.189.136.214
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source ~/.bashrc
            cd /srv/app/Frontend
            git pull origin frontend
            pnpm install
            pnpm build
            pm2 restart 3